### ISSUE TITLE
Error while running the comparing_pnn_ipfcns_hevc_best_mode.py --all

### ISSUE THREAD

**Issue by minhdl93** [thierrydumas/context_adaptive_neural_network_based_prediction#1]
Hello,

When I tried to run the code, it shows this error.
`FileNotFoundError: [Errno 2] No such file or directory: 'pnn/visualization/checking_predictions/kodak/width_target_4/fully_connected/single/luminance/1_0/masks_tr_0_0/masks_val_0_0/dictionary_performance.pkl'`

And I checked in this path 'pnn/visualization/checking_predictions/kodak/width_target_4/fully_connected/single/luminance/1_0/'

I can only saw the masks_tr_random and couldn't find the masks_tr_0_0.

Please help me!

**Comment by thierrydumas** [comment]
Hello,

The bug was due to the fact that the neural network models trained using fixed masks have not been pushed, only the neural network models trained via random masking have been pushed.
The script `comparing_pnn_hevc_best_mode.py` first skipped the computation of the dictionary of performance of the neural network model trained via fixed mask (0, 0) as the neural network model trained via fixed mask (0, 0) did not exist. Then, this script tried to load this dictionary of performance to fill a file ".csv". But, it could not find the dictionary of performance, and raised this exception.

The issue has been fixed in the last commit. Now, you can run `comparing_pnn_hevc_best_mode.py`. Note that you can only get a partially filled file ".csv" as the neural network models trained via fixed masks have not been pushed. I could not push all the models as they are too big. You should train the missing ones.

**Comment by minhdl93** [comment]
Thank you very much. The new commit solved the problem.
