### ISSUE TITLE
"cd hevc/hm_16_15_substitution/build/linux make"

### ISSUE THREAD

**Issue by OpencvW** [thierrydumas/context_adaptive_neural_network_based_prediction#3]
Hello,

When I compiled HEVC and two versions of HEVC including the neural networks on Linux using this code. 

"cd hevc/hm_16_15_substitution/build/linux
make"

I faced some errors. The error is related to the protobuf package in linux as shown in the image.

<img width="425" alt="KakaoTalk_20191206_103741748" src="https://user-images.githubusercontent.com/44459025/70288453-18f04200-1815-11ea-8556-dc281a1c5b2b.png">
<img width="430" alt="KakaoTalk_20191206_103813091" src="https://user-images.githubusercontent.com/44459025/70288455-18f04200-1815-11ea-9705-9e871d516fa8.png">

Please help me!

**Comment by thierrydumas** [comment]
Hi,

The error "undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const`" occurs because the definition of the functions declared in the Protobuf header files are not found. The error appears when compiling "TAppDecoder". In the Makefile "hevc/hm_16_15_substitution/build/linux/app/TAppDecoder/makefile", the directory at "path_to_dir_tf_c++/tensorflow-1.9.0/tensorflow/contrib/makefile/downloads/protobuf/src/.libs" is added to the list of library directories as it is supposed to contain the Protobuf library, named "libprotobuf.so". "path_to_dir_tf_c++" is the path to the directory storing the tensorflow repository in your system.

In your system, do you find "libprotobuf.so" in the directory at "path_to_dir_tf_c++/tensorflow-1.9.0/tensorflow/contrib/makefile/downloads/protobuf/src/.libs"?

**Comment by OpencvW** [comment]
Hi,

Thanks for your reply, I have "libprotobuf.so" in the directory at "path_to_dir_tf_c++/tensorflow-1.9.0/tensorflow/contrib/makefile/downloads/protobuf/src/.libs", and can you tell me what protobuf version and gcc version you used in this project?

![A%IY3R07N$(17G5XO8EY61N](https://user-images.githubusercontent.com/44459025/70856608-2eefb800-1f23-11ea-8403-8192f0930a9c.png)

**Comment by zhaorifa666** [comment]
> Hi,
> Thanks for your reply, I have "libprotobuf.so" in the directory at "path_to_dir_tf_c++/tensorflow-1.9.0/tensorflow/contrib/makefile/downloads/protobuf/src/.libs", and can you tell me what protobuf version and gcc version you used in this project?


Hi,

I am also studying this project, can we add a contact information to study together?In this way, problems can be communicated at any time

**Comment by DangLienMinh** [comment]
I also face the same problem.

**Comment by OpencvW** [comment]
problem solved， thank you！
