### ISSUE TITLE
Unable to open source file

### ISSUE THREAD

**Issue by zhaorifa666** [thierrydumas/context_adaptive_neural_network_based_prediction#6]
Hello,
  After I successfully run run_static_library_cmake.bat and run_static_library_build.bat in Windows, I try to compile "hevc\hm_16_15_substitution\build\HM_vc2015.sln", raises some errors: 
Unable to open source file "tensorflow/core/framework/graph.pb.h", "tensorflow/core/graph/graph_def_builder.h", "tensorflow/core/platform/logging.h", and so on. But some of these files are located "D:\context_adaptive\context_adaptive\tensorflow-1.9.0\tensorflow\contrib\cmake\build\tensorflow\core", and the others are located "D:\context_adaptive\context_adaptive\tensorflow-1.9.0\tensorflow\core" in my computers. Can you tell me how I should modify these errors? Thank you very much.

**Comment by thierrydumas** [comment]
Hello,

At the beginning of the compilation of "hevc\hm_16_15_substitution\build\HM_vc2015.sln", the macro `PathRelativeToTensorflow` is read from the file "hevc/hm_common/properties_substitution_switch.props". This macro defines the path to the directory named "tensorflow-1.9.0" relatively to the solution file being compiled. `PathRelativeToTensorflow = $(SolutionDir)\..\..\..\..\tensorflow-1.9.0`.
Can you check that, in your system, from the solution file "hevc\hm_16_15_substitution\build\HM_vc2015.sln", going down four levels in the directory tree, you get to a directory containing the root directory of the Tensorflow repository, i.e. "tensorflow-1.9.0" in your case?

**Comment by zhaorifa666** [comment]
Thanks for your reply!

My tensorflow-1.9.0 file is now located D:\context_adaptive\context_adaptive\ , how should I modify it? Thank you very much.

**Comment by zhaorifa666** [comment]
Thanks for your reply!

My "tensorflow-1.9.0" file is now located "D:\context_adaptive\context_adaptive\" , and "hevc" file is also  located "D:\context_adaptive\context_adaptive\", how should I modify it? Thank you very much.

**Comment by thierrydumas** [comment]
The directory named "tensorflow-1.9.0"  containing the Tensorflow repository is inside the directory at "D:\context_adaptive\context_adaptive". The directory named "hevc" shoud be inside the directory at "D:\context_adaptive\context_adaptive\context_adaptive_neural_network_based_prediction". The name "context_adaptive_neural_network_based_prediction" can be changed. The essential point is that, from the directory of the solution file, i.e. the one at "D:\context_adaptive\context_adaptive\context_adaptive_neural_network_based_prediction\hevc\hm_16_15_substitution\build", going down four levels in the directory tree, the program reaches "D:\context_adaptive\context_adaptive", which contains the directory containing the Tensorflow repository. So the header files you mentioned will be found.

**Comment by zhaorifa666** [comment]
Thanks for your reply!

According to your instructions, the header files have been found.  When I compile "hevc\hm_16_15_substitution\build\HM_vc2015.sln",  raises  errors "Error C3861 "PyString_FromString" : identifier not found" in the file "hevc\hm_common\c++\source_commom\ interface_c_python.cpp". My python version is 3.7.3, how should I modify it? Thank you very much.

**Comment by thierrydumas** [comment]
Thank you for the feedback.

As you guessed, the problem is related to the version of Python. I always compiled "hevc\hm_16_15_substitution\build\HM_vc2015.sln" by linking to "libpython27.so" in Linux (to "C:\Programs Files\Python27\python.exe" in Windows). Tomorrow, I will push a new commit to fix this issue.

With regards,

Thierry Dumas.

________________________________
De : zhaorifa666 <notifications@github.com>
Envoyé : mardi 31 décembre 2019 03:21
À : thierrydumas/context_adaptive_neural_network_based_prediction <context_adaptive_neural_network_based_prediction@noreply.github.com>
Cc : Thierry Dumas <dumas--thierry@hotmail.fr>; Comment <comment@noreply.github.com>
Objet : Re: [thierrydumas/context_adaptive_neural_network_based_prediction] Unable to open source file (#6)


Thanks for your reply!

According to your instructions, the header files have been found. When I compile "hevc\hm_16_15_substitution\build\HM_vc2015.sln", raises errors "Error C3861 "PyString_FromString" : identifier not found" in the file "hevc\hm_common\c++\source_commom\ interface_c_python.cpp". My python version is 3.7.3, how should I modify it? Thank you very much.

**Comment by thierrydumas** [comment]
Thank you for your feedback.

A new commit was pushed. It should fix your problem as now the two versions of HEVC with the neural networks can be compiled with either Python2.x or Python3.x.
Warning! The default configurations for the compilations consider Python2.7. On Windows, to use Python3.6 for instance, in the file "hevc/hm_common/properties_substitution_switch.props", the macro `PathAbsoluteToPython` must be set to the path to the directory containing the "python.exe" of Python36. Moreover, in the solution files "hevc/hm_16_15_substitution/build/HM_vc2015.sln" and "hevc/hm_16_15_switch/build/HM_vc2015.sln", for each of the three projects "TAppEncoder", "TAppDecoder", and "TAppDecoderAnalyzer", in the project property, in "linker", the library "python27.lib" should be changed.

**Comment by zhaorifa666** [comment]
Thank you very much!

My problem has been fixed with your help. Moreover, I have sent  an email at dumas--thierry@hotmail.fr to request the model of the neural network predicting blocks of size 64x64. Thank you very much!
